name: MERN Stack Deployment

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies and Build Client
        run: |
          cd client
          npm install
          npm run build

      - name: Install Dependencies and Start Server
        run: |
          cd ../server
          npm install
          npm start

