name: MERN Stack Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies and Build Client
        run: |
          cd client
          npm install
          npm run build

      - name: Install Dependencies for Server
        run: |
          cd ../server
          npm install

      - name: Start Server
        run: |
          cd ../server
          npm start

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  PORT: ${{ secrets.PORT }}
